services:
  - type: web
    name: sexyselfies-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build &&
      cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health