services:
  - type: web
    name: sexyselfies-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://sexyselfies-frontend.onrender.com
    healthCheckPath: /health
    # Render-specific optimizations
    maxmemory: 512MB
