services:
  # Monorepo - Backend serving both API and Frontend
  - type: web
    name: sexyselfies-app
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health